import DxfWriter from "dxf-writer";
import { calculateCaseGeometry } from "./geometry.js";
import { state } from "./state.js";
import { HP_TO_MM } from "./constants.js";

export function generateSVG() {
  const geometry = calculateCaseGeometry();
  const padding = 10;
  const scale = 1;

  const width = (geometry.maxX + padding * 2) * scale;
  const height = (geometry.maxY + padding * 2) * scale;

  function tx(x) {
    return (x + padding) * scale;
  }
  function ty(y) {
    return (geometry.maxY - y + padding) * scale;
  }

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}">
  <title>Eurorack Case Side Panel</title>
  <desc>Generated by DIY Eurorack Case Planner</desc>
  
  <!-- Cut lines (outline) -->
  <g id="outline" stroke="#000000" stroke-width="0.5" fill="none">
    <path d="`;

  const outline = geometry.outline;
  svg += `M ${tx(outline[0].x)} ${ty(outline[0].y)}`;
  for (let i = 1; i < outline.length; i++) {
    svg += ` L ${tx(outline[i].x)} ${ty(outline[i].y)}`;
  }
  svg += ` Z" />
  </g>
  
  <!-- Drill holes -->
  <g id="drill-holes" stroke="#aa3333" stroke-width="0.3" fill="none">`;

  const drillRadius = 2.1; // 4.2mm diameter for M4 screws
  geometry.drillHoles.forEach((hole, i) => {
    svg += `
    <circle cx="${tx(hole.x)}" cy="${ty(hole.y)}" r="${drillRadius}" />`;
  });

  svg += `
  </g>
</svg>`;

  return svg;
}

export function generateDXF() {
  const geometry = calculateCaseGeometry();
  const dxf = new DxfWriter();

  dxf.addLayer("OUTLINE", DxfWriter.ACI.WHITE, "CONTINUOUS");
  dxf.addLayer("DRILL_HOLES", DxfWriter.ACI.RED, "CONTINUOUS");

  dxf.setActiveLayer("OUTLINE");
  const outline = geometry.outline;
  for (let i = 0; i < outline.length - 1; i++) {
    dxf.drawLine(outline[i].x, outline[i].y, outline[i + 1].x, outline[i + 1].y);
  }

  dxf.setActiveLayer("DRILL_HOLES");
  const drillRadius = 2.1; // 4.2mm diameter for M4 screws
  geometry.drillHoles.forEach((hole) => {
    dxf.drawCircle(hole.x, hole.y, drillRadius);
  });

  return dxf.toDxfString();
}

export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadSVG() {
  const svg = generateSVG();
  downloadFile(svg, "eurorack-case-side.svg", "image/svg+xml");
}

export function downloadDXF() {
  const dxf = generateDXF();
  downloadFile(dxf, "eurorack-case-side.dxf", "application/dxf");
}
