import DxfWriter from "dxf-writer";
import { calculateCaseGeometry } from "./geometry.js";
import { state } from "./state.js";
import { HP_TO_MM } from "./constants.js";

let includeCutPanels = true;

export function setIncludeCutPanels(value) {
  includeCutPanels = value;
}

export function generateSVG() {
  const geometry = calculateCaseGeometry();
  const padding = 10;
  const panelSpacing = 15;
  const scale = 1;

  let cutPanelsTotalWidth = 0;
  let cutPanelsMaxHeight = 0;
  
  if (includeCutPanels) {
    geometry.cutPanels.forEach((panel, index) => {
      cutPanelsTotalWidth += panel.height;
      if (index < geometry.cutPanels.length - 1) {
        cutPanelsTotalWidth += panelSpacing;
      }
    });
    cutPanelsMaxHeight = Math.max(...geometry.cutPanels.map(p => p.width));
  }
  
  const totalWidth = includeCutPanels ? Math.max(geometry.maxX, cutPanelsTotalWidth) : geometry.maxX;
  const totalHeight = includeCutPanels ? geometry.maxY + padding + cutPanelsMaxHeight : geometry.maxY;

  const width = (totalWidth + padding * 2) * scale;
  const height = (totalHeight + padding * 2) * scale;

  function tx(x) {
    return (x + padding) * scale;
  }
  function ty(y) {
    return (totalHeight - y + padding) * scale;
  }

  const sideYOffset = includeCutPanels ? cutPanelsMaxHeight + padding : 0;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}">
  <title>Eurorack Case Panels</title>
  <desc>Generated by DIY Eurorack Case Planner</desc>
  
  <!-- Side Panel - Cut lines (outline) -->
  <g id="side-panel-outline" stroke="#000000" stroke-width="0.5" fill="none">
    <path d="`;

  const outline = geometry.outline;
  svg += `M ${tx(outline[0].x)} ${ty(outline[0].y + sideYOffset)}`;
  for (let i = 1; i < outline.length; i++) {
    svg += ` L ${tx(outline[i].x)} ${ty(outline[i].y + sideYOffset)}`;
  }
  svg += ` Z" />
  </g>
  
  <!-- Side Panel - Drill holes -->
  <g id="side-panel-drill-holes" stroke="#aa3333" stroke-width="0.3" fill="none">`;

  const drillRadius = 2.1;
  geometry.drillHoles.forEach((hole) => {
    svg += `
    <circle cx="${tx(hole.x)}" cy="${ty(hole.y + sideYOffset)}" r="${drillRadius}" />`;
  });

  svg += `
  </g>`;

  if (includeCutPanels) {
    svg += `
  
  <!-- Cut Panels (Front, Bottom, Back, Top) -->
  <g id="cut-panels" stroke="#000000" stroke-width="0.5" fill="none">`;

    let currentX = 0;
    geometry.cutPanels.forEach((panel) => {
      const x1 = currentX;
      const y2 = panel.width;
      
      svg += `
    <rect x="${tx(x1)}" y="${ty(y2)}" width="${panel.height}" height="${panel.width}" />`;
      
      currentX += panel.height + panelSpacing;
    });

    svg += `
  </g>`;
  }

  svg += `
</svg>`;

  return svg;
}

export function generateDXF() {
  const geometry = calculateCaseGeometry();
  const dxf = new DxfWriter();
  const panelSpacing = 15;

  dxf.addLayer("SIDE_PANEL", DxfWriter.ACI.WHITE, "CONTINUOUS");
  dxf.addLayer("DRILL_HOLES", DxfWriter.ACI.RED, "CONTINUOUS");
  if (includeCutPanels) {
    dxf.addLayer("CUT_PANELS", DxfWriter.ACI.CYAN, "CONTINUOUS");
  }

  const cutPanelsMaxHeight = includeCutPanels ? Math.max(...geometry.cutPanels.map(p => p.width)) : 0;
  const sideYOffset = includeCutPanels ? cutPanelsMaxHeight + panelSpacing : 0;

  dxf.setActiveLayer("SIDE_PANEL");
  const outline = geometry.outline;
  for (let i = 0; i < outline.length - 1; i++) {
    dxf.drawLine(
      outline[i].x,
      outline[i].y + sideYOffset,
      outline[i + 1].x,
      outline[i + 1].y + sideYOffset
    );
  }

  dxf.setActiveLayer("DRILL_HOLES");
  const drillRadius = 2.1;
  geometry.drillHoles.forEach((hole) => {
    dxf.drawCircle(hole.x, hole.y + sideYOffset, drillRadius);
  });

  if (includeCutPanels) {
    dxf.setActiveLayer("CUT_PANELS");
    let currentX = 0;
    geometry.cutPanels.forEach((panel) => {
      const x1 = currentX;
      const y1 = 0;
      const x2 = currentX + panel.height;
      const y2 = panel.width;
      
      dxf.drawLine(x1, y1, x2, y1);
      dxf.drawLine(x2, y1, x2, y2);
      dxf.drawLine(x2, y2, x1, y2);
      dxf.drawLine(x1, y2, x1, y1);
      
      currentX += panel.height + panelSpacing;
    });
  }

  return dxf.toDxfString();
}

export function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadSVG() {
  const svg = generateSVG();
  downloadFile(svg, "eurorack-case-side.svg", "image/svg+xml");
}

export function downloadDXF() {
  const dxf = generateDXF();
  downloadFile(dxf, "eurorack-case-side.dxf", "application/dxf");
}
